### ISSUE TITLE
Keep track of created users

### ISSUE THREAD

**Issue by IoanDascalu** [wertzy/shoporswap#37]
Will keep track of the users created, keeping information like username and passwords.

How to demo: A person will create an account, and the be able to log into that account at a later time.

**Comment by jmoczynski** [comment]
_Time Record_ **(total time: 28 minutes = 0.47 hours)**
**9:00-9:28 (28 minutes)** updated ShopOrSwap tests for JSON integration, implemented methods to incorporate JSON, updated some implementations
