### ISSUE TITLE
User Class

### ISSUE THREAD

**Issue by jmoczynski** [wertzy/shoporswap#4]
How to demo: manual testing during code review which allows people to attempt to create users

Description: Implement some user class with flexibility to be a Shopper, Seller, or Swapper. The class should include at least an email address, a shipping address, a password as input. The class should include shopper, seller, and swapper ratings.

**Comment by ptkaczyk** [comment]
Create a user account, and be able to access its information.

**Comment by jmoczynski** [comment]
implemented User.isAccountNameValid, User.isPasswordValid, and User.isRatingValid; added some comments in User.java (timeframe: 4:49-5:09, 20 minutes)

**Comment by jmoczynski** [comment]
began implementation of and updated tests for User, Seller, Shopper, Swapper (timeframe: 10:25-11:05, 40 minutes)

**Comment by jmoczynski** [comment]
Need to discuss difference between sellers, swappers, and shoppers with development team.
