### ISSUE TITLE
Product Class

### ISSUE THREAD

**Issue by jmoczynski** [wertzy/shoporswap#5]
How to Demo: manual testing during code review which allows people to attempt to create users

Description: A Product class needs to be developed to hold information about a product being sold. The product should include at least a name, description, price, and owner.

**Comment by ptkaczyk** [comment]
Create a piece of clothing which is able to perform a piece of clothing's properties.

**Comment by jmoczynski** [comment]
added initial class diagram for Product class (represents clothing) (time: 10:27-10:37, 10 minutes)
